name: Test py

on:
  push:
    branches: 
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install python
      run: sudo apt install python3 -y
      
    - name: Git clone
      uses: actions/checkout@v1
    
    - name: Chmod
      run: chmod a+x ./test.py
      
    - name: cat
      run: cat test.py
      
    - name: Python
      run: python3 test.py
