name: Test py

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install python
      run: sudo apt install python3 -y
      
    - name: Git clone
      uses: actions/checkout@v1
    
    - name: Chmod
      run: chmod a+x ./test.py
    - name: End
      run: chmod a+x ./end.py
    - name: Wert
      run: chmod a+x ./1.py
      
    - name: Python
      run: python3 test.py
    
    - name: End.py
      run: python3 end.py
    
    - name: 1.py
      run: python3 1.py
